sudo: required
language: generic
dist: xenial 

addons:
  apt:
    packages:
      libc6-i386      
      git cmake sox libsamplerate0-dev portaudio19-dev libsndfile-dev libhamlib-dev
      
script:
    - cmake --version
    - export FREEBEACONDIR=${PWD}
    - export CODEC2DIR=${FREEBEACONDIR}/codec2
    - git clone https://github.com/drowe67/codec2.git
    - cd codec2 && mkdir -p build_linux && cd build_linux
    - cmake .. && make
    - cd ${FREEBEACONDIR}
    - mkdir -p build_linux && cd build_linux
    - cmake -DCODEC2_BUILD_DIR=${CODEC2DIR}/build_linux .. && make VERBOSE=1
    - ldd freebeacon | grep codec2
    - ./freebeacon -h

